version: "3.9"
services:
  apps:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/app
    ports:
      - 3000:3000
      - 2000:2000
  db:
    image: postgres:14.1-alpine3.15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=filehosting
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: